// Generated by update-gallery.py
window.aylolGallery = [
  {
    "src": "media/gallery/Hair/video2 (2).mp4",
    "type": "video",
    "category": "hair",
    "alt": "عناية الشعر — لمسة أيلول",
    "brightness": 1,
    "order": 0
  },
  {
    "src": "media/gallery/Nails/nail5.jpeg",
    "type": "image",
    "category": "nails",
    "alt": "لمسات بحرية بالأزرق واللؤلؤ",
    "brightness": 1.06,
    "order": 1
  },
  {
    "src": "media/gallery/Nails/nail.1.jpeg",
    "type": "image",
    "category": "nails",
    "alt": "فرنش ناعم بتفاصيل زهرية",
    "brightness": 1.15,
    "order": 2
  },
  {
    "src": "media/gallery/Nails/nail2.jpeg",
    "type": "image",
    "category": "nails",
    "alt": "درجات وردية ولمعة أنيقة",
    "brightness": 1.07,
    "order": 3
  },
  {
    "src": "media/gallery/Nails/nail 6.jpeg",
    "type": "image",
    "category": "nails",
    "alt": "أناقة الأحمر بلمسات ذهبية",
    "brightness": 1.12,
    "order": 4
  },
  {
    "src": "media/gallery/Nails/nail3.jpeg",
    "type": "image",
    "category": "nails",
    "alt": "ركن الأظافر وتشكيلة التصاميم",
    "brightness": 1.09,
    "order": 5
  },
  {
    "src": "media/gallery/Nails/nail4.jpeg",
    "type": "image",
    "category": "nails",
    "alt": "تشكيلة ألوان لكل إطلالة",
    "brightness": 1.19,
    "order": 6
  },
  {
    "src": "media/gallery/Nails/nail 7.jpeg",
    "type": "image",
    "category": "nails",
    "alt": "تفاصيل من ركن العناية بالأظافر",
    "brightness": 1.18,
    "order": 7
  }
];
