"""Run: python media/gallery/update-gallery.py after adding local photos."""
from pathlib import Path
import json

root = Path(__file__).resolve().parent
settings_path = root / "photo-settings.json"
settings = json.loads(settings_path.read_text(encoding="utf-8")) if settings_path.exists() else {}
labels = {"Makeup": "إطلالة ميكب", "Hair": "تسريحة شعر", "Brides": "إطلالة عروس", "Nails": "فن الأظافر"}
entries = []
for folder, label in labels.items():
    directory = root / folder
    directory.mkdir(exist_ok=True)
    for photo in sorted(directory.rglob("*")):
        if photo.is_file() and photo.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp", ".avif", ".mp4", ".webm"}:
            relative = photo.relative_to(root).as_posix()
            options = settings.get(relative, {})
            entries.append({"src": "media/gallery/" + relative,
                            "type": "video" if photo.suffix.lower() in {".mp4", ".webm"} else "image",
                            "category": folder.lower(), "alt": options.get("alt", f"{label} — أيلول بيوتي"),
                            "brightness": options.get("brightness", 1), "order": options.get("order", 100)})
entries.sort(key=lambda entry: entry["order"])
(root / "gallery.js").write_text(
    "// Generated by update-gallery.py\nwindow.aylolGallery = " +
    json.dumps(entries, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")
print(f"Updated gallery with {len(entries)} local photos.")
